# Classification

07 July 2026, Tuesday

In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [34]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv')

In [35]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [36]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [38]:
df = df.dropna(subset= ['Survived'])

In [39]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [40]:
X = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Fare']]
y = df['Survived']

In [41]:
X.shape

(891, 5)

In [42]:
y.shape

(891,)

In [43]:
X['Sex']

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str

In [44]:
X['Sex'] = X['Sex'].map({'male': 1, 'female': 0})

In [45]:
X['Sex']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [46]:
X['Age'].isna().sum()

np.int64(177)

In [47]:
X['Age'] = X['Age'].fillna(X['Age'].median())

In [48]:
X['Age'].isna().sum()

np.int64(0)

### Train-Test Split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Creating Model

In [50]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [51]:
y_pred = rf_classifier.predict(X_test)

In [59]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.80

In [58]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       105
           1       0.78      0.73      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179

In [63]:
X_test

     Pclass  Sex   Age  SibSp     Fare
709       3    1  28.0      1  15.2458
439       2    1  31.0      0  10.5000
840       3    1  20.0      0   7.9250
720       2    0   6.0      0  33.0000
39        3    0  14.0      1  11.2417
..      ...  ...   ...    ...      ...
433       3    1  17.0      0   7.1250
773       3    1  28.0      0   7.2250
25        3    0  38.0      1  31.3875
84        2    0  17.0      0  10.5000
10        3    0   4.0      1  16.7000

[179 rows x 5 columns]

In [65]:
X_test.iloc[0:1]

     Pclass  Sex   Age  SibSp     Fare
709       3    1  28.0      1  15.2458

In [61]:
X_test.iloc[0:1]

     Pclass  Sex   Age  SibSp     Fare
709       3    1  28.0      1  15.2458