# Cleaning Scraped Data

06 July 2026, Monday

## Raw Scraped Data

In [14]:
data = "    webscraping using python    "

### White Space Removal

In [15]:
clean_data = data.strip()
clean_data

'webscraping using python'

In [20]:
import re
re.sub(r'\s+', ' ', clean_data)

'webscraping using python'

### Special Character Removal

In [25]:
humidity = "  70%  "
# Use replace function
clean_humidity = humidity.replace("%", "").strip()
clean_humidity

'70'

### Converting Data Type

In [26]:
clean_humidity

'70'

In [33]:
humidity_int = int(clean_humidity)
humidity_int

70

In [34]:
# Checking datatype
type(humidity_int)

int

### Text Lowercasing

In [36]:
text = 'PYTHON WEB SCRAPING'
clean_text = text.lower()
print(clean_text)

python web scraping

### Removing Duplicates from a pandas dataframe

In [38]:
import pandas as pd

In [41]:
df = pd.DataFrame({'Product': ["Laptop", "Laptop", "Phone"]})
df

  Product
0  Laptop
1  Laptop
2   Phone

In [45]:
df.drop_duplicates(inplace=True)

In [46]:
df

  Product
0  Laptop
2   Phone